name: ci

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STATICRYPT_PASSWORD: ${{ secrets.STATICRYPT_PASSWORD }}
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Restore optimized assets
        id: cache-assets-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ./node_modules/.astro/assets
          key: astro-assets
      - name: Install, build, and upload your site output
        uses: withastro/action@v2
      - name: Save optimized assets
        id: cache-assets-save
        uses: actions/cache/save@v4
        with:
          path: |
            ./node_modules/.astro/assets
          key: astro-assets

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4